version: '3'

services:
  weather-forecast-app:
    image: weather-forecast-app
    build:
      context: ./
      target: dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
