services:
  weather-forecast-app:
    image: weather-forecast-app
    build:
      context: ./
      target: dev
      args:
        - VITE_GEOCODING_API_BASE_URL=${VITE_GEOCODING_API_BASE_URL}
        - VITE_FORECAST_API_BASE_URL=${VITE_FORECAST_API_BASE_URL}
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
